version: '3.1'

networks:
  my_network:
    external: true

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
